[build]
  environment = { NETLIFY_USE_YARN = "true" }

[dev]
  publish = "build"
  command = "yarn build"
  environment = { NETLIFY_USE_YARN = "true" }

[[headers]]
  for = "/.well-known/nostr.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
    Access-Control-Allow-Headers = "Content-Type,x-prerender"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/*"
  function = "hello"